---
- name: Install podman
  ansible.builtin.dnf:
    name: podman
  when: ansible_os_family == 'RedHat'

- name: Install podman
  ansible.builtin.apt:
    name: podman
  when: ansible_os_family == 'Debian'

- name: Ensure superset and clickhouse data dir exists
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0750"
    recurse: true
    state: directory
  with_items:
    - /etc/superset
    - /var/lib/superset/data
    - /var/lib/superset/pgwal
    - /var/lib/superset/pgdata
    - /var/lib/clickhouse/data
    - /var/lib/clickhouse/logs

- name: Create superset network
  ansible.builtin.copy:
    dest: /etc/containers/systemd/superset.network
    mode: "0640"
    content: |
      [Network]
      NetworkName=superset

- name: Install postgers for superset
  ansible.builtin.copy:
    dest: /etc/containers/systemd/superset-pg.container
    mode: "0640"
    content: |
      [Unit]
      Description=postgresql for superset

      [Install]
      WantedBy=default.target

      [Container]
      Image=docker.io/postgres:18-alpine
      ContainerName=superset-pg
      Network=superset.network
      Volume=/var/lib/superset/pgwal:/pgwal:U,rw,Z
      Volume=/var/lib/superset/pgdata:/pgdata:U,rw,Z
      Environment=POSTGRES_DB=superset
      Environment=POSTGRES_USER=superset
      Environment=POSTGRES_PASSWORD=superset123
      Environment=PGDATA=/pgdata
      Environment=POSTGRES_INITDB_WALDIR=/pgwal

      [Service]
      Restart=on-failure

- name: Copy superset config
  ansible.builtin.copy:
    src: superset_config.py
    dest: /etc/superset/
    mode: "0640"

- name: Install superset
  ansible.builtin.copy:
    dest: /etc/containers/systemd/superset.container
    mode: "0640"
    content: |
      [Unit]
      Description=superset

      [Install]
      WantedBy=default.target

      [Container]
      Image=docker.io/shadowlegend/superset:6.0.0
      ContainerName=superset
      Network=superset.network
      PublishPort=127.0.0.1:8088:8088
      Volume=/etc/superset/superset_config.py:/superset_config.py
      Volume=/var/lib/superset/data:/app/superset_home:U,rw,Z
      Exec=bash -c 'superset db upgrade && superset init && /app/docker/entrypoints/run-server.sh'
      Environment=DATABASE_DB=superset
      Environment=REDIS_HOST=dragonfly
      Environment=PGHOST=superset-pg
      Environment=PGUSER=superset
      Environment=PGPASSWORD=superset123
      Environment=SUPERSET_CONFIG_PATH=/superset_config.py
      Environment=DEV_MODE=false
      Environment=FLASK_DEBUG=false
      Environment=SUPERSET_LOAD_EXAMPLES=no
      Environment=SUPERSET_SECRET_KEY={{ analytic_superset_secret_key }}
      Environment=SSO_OIDC_CLIENT_ID={{ analytic_superset_oidc_client_id }}
      Environment=SSO_OIDC_CLIENT_SECRET={{ analytic_superset_oidc_client_secret }}
      Environment=SSO_OIDC_JWKS_URI={{ analytic_superset_oidc_jwks_uri }}
      Environment=SSO_OIDC_API_BASE_URL={{ analytic_superset_oidc_api_base_url }}
      Environment=SSO_OIDC_ACCESS_TOKEN_URL={{ analytic_superset_oidc_access_token_url }}
      Environment=SSO_OIDC_AUTHORIZE_URL={{ analytic_superset_oidc_authorize_url }}

      [Service]
      Restart=on-failure

- name: Ensure clickhouse config dir exists
  ansible.builtin.file:
    path: /etc/clickhouse-server/config.d
    state: directory
    recurse: true

- name: Add clickhouse trace log disk config
  ansible.builtin.copy:
    dest: /etc/clickhouse-server/config.d/trace-log.xml
    mode: "0640"
    content: |
      <clickhouse>
        <max_table_size_to_drop>60G</max_table_size_to_drop>
        <trace_log replace="1">
          <database>system</database>
          <table>trace_log</table>
          <partition_by>toYYYYMM(event_date)</partition_by>
          <flush_interval_milliseconds>7500</flush_interval_milliseconds>
          <max_size_rows>1048576</max_size_rows>
          <reserved_size_rows>8192</reserved_size_rows>
          <buffer_size_rows_flush_threshold>524288</buffer_size_rows_flush_threshold>
          <flush_on_crash>false</flush_on_crash>
          <symbolize>false</symbolize>
          <engine>Engine = MergeTree PARTITION BY event_date ORDER BY event_time TTL event_date + interval 4 day</engine>
        </trace_log>
      </clickhouse>

- name: Install clickhouse
  ansible.builtin.copy:
    dest: /etc/containers/systemd/clickhouse.container
    mode: "0640"
    content: |
      [Unit]
      Description=clickhouse

      [Install]
      WantedBy=default.target

      [Container]
      Image=docker.io/clickhouse/clickhouse-server:25.11-alpine
      ContainerName=clickhouse
      Network=superset.network
      Volume=/var/lib/clickhouse/data:/var/lib/clickhouse:U,rw,Z
      Volume=/var/lib/clickhouse/logs:/var/log/clickhouse-server:U,rw,Z
      Volume=/etc/clickhouse-server/config.d/trace-log.xml:/etc/clickhouse-server/config.d/trace-log.xml:ro,z
      Environment=CLICKHOUSE_DB=superset
      Environment=CLICKHOUSE_USER=superset
      Environment=CLICKHOUSE_PASSWORD=superset123
      Environment=CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

      [Service]
      Restart=on-failure

- name: Ensure all services started
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    daemon_reload: true
  with_items:
    - clickhouse
    - superset
    - superset-pg

- name: Install processors
  ansible.builtin.template:
    src: processor.container.tpl
    dest: /etc/containers/systemd/{{ item.name }}.container
    mode: "0640"
  loop: analytic_ais_data_nexus_processors

- name: Ensure processors started
  ansible.builtin.systemd_service:
    name: "{{ item.name }}"
    state: started
    daemon_reload: true
  loop: analytic_ais_data_nexus_processors
